services:
  postgres:
    container_name: postgres
    image: "postgres:11-bullseye"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo
    volumes:
      - postgres-data:/var/lib/postgres
  redis:
    container_name: redis
    image: "redis:7.2.3-bookworm"
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
